/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sr;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args)
     { Aragorn aragorn = new Aragorn("aragorn", 10, 10, 5, 40, true);
        Orc orc = new Orc("orc", 10, 10, 5, 60, false);
     
        Mapa mapa = new Mapa();
    try{
        mapa.inserePersonagem(orc, 2);
    }
    catch (PersonagemJaEstaNoMapaException e)
    {

    }  

        
       //Gandalf gandalf = new Gandalf("gandalf", 6, 4, 10, 80, true);
       try
       { 
         Simular s = new Simular();
         s.simula(mapa);
       }
       catch (Exception e)
       {

       }
       catch (Exception e)
       {
        
       }



    }
}
